# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  lsb2-eureka-server:
    labels:
      lsb2.template.description: "Eureka Server for local environment"
      lsb2.chat.version: $TAG
    image: "jghamburg/lsb2-eureka-server:$TAG"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-eureka-server.jar
    ports:
      - "8761:8080" # web port
    environment:
      PROFILE: "default"
      PORT: 8080
