# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-eureka-server:
    labels:
      de.otto.template.description: "Eureka Server for local environment"
      de.otto.drop.brandshopupdater.version: "local"
    image: "eureka-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8761:8761" # web port
    environment:
      PROFILE: "local"
      OTTO_GROUP: "local"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true


